# Generated by Django 3.2.5 on 2021-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='author',
            field=models.CharField(choices=[('STAFF', 'STAFF'), ('MEMBER', 'MEMBER'), ('ANON', 'ANON')], max_length=200),
        ),
    ]
